### ISSUE TITLE
Doesn't compile with mbed TLS 2.4 on LEDE (OpenWRT fork)

### ISSUE THREAD

**Issue by diizzyy** [umurmur/umurmur#102]
configure: loading site script /home/diizzy/clean-up/source/include/site/mips
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mips-openwrt-linux-strip... mips-openwrt-linux-musl-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... mips-openwrt-linux-gnu
checking whether make supports nested variables... (cached) yes
checking for mips-openwrt-linux-gcc... mips-openwrt-linux-musl-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether mips-openwrt-linux-musl-gcc accepts -g... yes
checking for mips-openwrt-linux-musl-gcc option to accept ISO C89... none needed
checking whether mips-openwrt-linux-musl-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of mips-openwrt-linux-musl-gcc... gcc3
checking how to run the C preprocessor... mips-openwrt-linux-musl-gcc -E
checking for grep that handles long lines and -e... /home/diizzy/clean-up/source/staging_dir/host/bin/grep
checking for egrep... /home/diizzy/clean-up/source/staging_dir/host/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking google/protobuf-c/protobuf-c.h usability... yes
checking google/protobuf-c/protobuf-c.h presence... yes
checking for google/protobuf-c/protobuf-c.h... yes
checking for protobuf_c_message_init in -lprotobuf-c... yes
checking libconfig.h usability... yes
checking libconfig.h presence... yes
checking for libconfig.h... yes
checking for config_init in -lconfig... yes
checking for clock_gettime... yes
checking mbedtls/ssl.h usability... yes
checking mbedtls/ssl.h presence... yes
checking for mbedtls/ssl.h... yes
checking mbedtls/version.h usability... yes
checking mbedtls/version.h presence... yes
checking for mbedtls/version.h... yes
checking for mbedtls_ssl_init in -lmbedtls... yes
checking for mbedtls_cipher_setup in -lmbedcrypto... yes
checking for mbedtls_x509_crt_init in -lmbedx509... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking sys/poll.h usability... yes
checking sys/poll.h presence... yes
checking for sys/poll.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for uid_t in sys/types.h... yes
checking for inline... inline
checking for int32_t... yes
checking for int64_t... yes
checking for size_t... (cached) yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for ftruncate... yes
checking for gettimeofday... (cached) yes
checking for inet_ntoa... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for socket... yes
checking for strdup... yes
checking for strrchr... yes
checking for uname... yes
checking for poll... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: executing depfiles commands

rm -f /home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test/.configured_*
touch /home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test/.configured_yyyyyyy
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap /home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test:umurmur-2016-11-26-test -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/diizzy/clean-up/source/staging_dir/target-mips_24kc_musl-1.1.15/usr/include -I/home/diizzy/clean-up/source/staging_dir/target-mips_24kc_musl-1.1.15/include -I/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/usr/include -I/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify -I/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap /home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test:umurmur-2016-11-26-test -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/diizzy/clean-up/source/staging_dir/target-mips_24kc_musl-1.1.15/usr/include -I/home/diizzy/clean-up/source/staging_dir/target-mips_24kc_musl-1.1.15/include -I/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/usr/include -I/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify -I/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include " LDFLAGS="-L/home/diizzy/clean-up/source/staging_dir/target-mips_24kc_musl-1.1.15/usr/lib -L/home/diizzy/clean-up/source/staging_dir/target-mips_24kc_musl-1.1.15/lib -L/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/usr/lib -L/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/lib -znow -zrelro " make -j1 -C /home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test/. AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test:umurmur-2016-11-26-test -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CROSS="mips-openwrt-linux-musl-" ARCH="mips" ;
make[4]: Entering directory '/home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test'
Making all in src
make[5]: Entering directory '/home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test/src'
make  all-am
make[6]: Entering directory '/home/diizzy/clean-up/source/build_dir/target-mips_24kc_musl-1.1.15/umurmur-mbedtls/umurmur-2016-11-26-test/src'
  CC       client.o
In file included from client.c:31:0:
/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^
In file included from client.h:42:0,
                 from log.h:35,
                 from client.c:38:
/home/diizzy/clean-up/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^
In file included from client.h:50:0,
                 from log.h:35,
                 from client.c:38:
client.c: In function 'Client_read':
ssl.h:120:28: error: 'MBEDTLS_ERR_NET_RECV_FAILED' undeclared (first use in this function)
 #define SSLI_ERROR_SYSCALL MBEDTLS_ERR_NET_RECV_FAILED
                            ^
client.c:522:44: note: in expansion of macro 'SSLI_ERROR_SYSCALL'
     if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_SYSCALL) {
                                            ^
ssl.h:120:28: note: each undeclared identifier is reported only once for each function it appears in
 #define SSLI_ERROR_SYSCALL MBEDTLS_ERR_NET_RECV_FAILED
                            ^
client.c:522:44: note: in expansion of macro 'SSLI_ERROR_SYSCALL'
     if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_SYSCALL) {
                                            ^
ssl.h:119:30: error: 'MBEDTLS_ERR_NET_CONN_RESET' undeclared (first use in this function)
 #define SSLI_ERROR_CONNRESET MBEDTLS_ERR_NET_CONN_RESET
                              ^
client.c:529:49: note: in expansion of macro 'SSLI_ERROR_CONNRESET'
     else if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_CONNRESET) {
                                                 ^
client.c: In function 'Client_write':
ssl.h:120:28: error: 'MBEDTLS_ERR_NET_RECV_FAILED' undeclared (first use in this function)
 #define SSLI_ERROR_SYSCALL MBEDTLS_ERR_NET_RECV_FAILED
                            ^
client.c:585:43: note: in expansion of macro 'SSLI_ERROR_SYSCALL'
    if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_SYSCALL) {
                                           ^
ssl.h:119:30: error: 'MBEDTLS_ERR_NET_CONN_RESET' undeclared (first use in this function)
 #define SSLI_ERROR_CONNRESET MBEDTLS_ERR_NET_CONN_RESET
                              ^
client.c:588:48: note: in expansion of macro 'SSLI_ERROR_CONNRESET'
    else if (SSLi_get_error(client->ssl, rc) == SSLI_ERROR_CONNRESET) {
                                                ^
Makefile:413: recipe for target 'client.o' failed
make[6]: *** [client.o] Error 1

If there's anymore information you need please do tell.

**Comment by diizzyy** [comment]
@fmorgner 
Are you able to have a look at this?
If you're busy/not interested that's fine, just want to know status as PolarSSL is EOL

**Comment by thess** [comment]
Simple fix for current mbed TLS release...

>--- a/src/ssl.h
+++ b/src/ssl.h
@@ -90,7 +90,7 @@ typedef       ssl_context SSL_handle_t;
 >
 >#elif defined(USE_MBEDTLS)
 #include <mbedtls/ssl.h>
-#include <mbedtls/net.h>
+#include <mbedtls/net_sockets.h>
 #include <mbedtls/version.h>
 >
 >#if defined(MBEDTLS_VERSION_MAJOR)

**Comment by fmorgner** [comment]
If Polar is EOL we should consider removing it. I assume that mbed is still going strong?

**Comment by diizzyy** [comment]
Yes, Mbed TLS is very much alive :)

**Comment by fmorgner** [comment]
Are there any platforms that still rely on Polar?
