### ISSUE TITLE
Private Key protected by Password

### ISSUE THREAD

**Issue by juadde** [umurmur/umurmur#117]
Is there a configuration option to read the private key with a password?
At first I thought `password="";` was it but it seems that this is the default password...

[EDIT] I'll generate private keys without password, but I will let this question open as it may be useful for somebody else...

**Comment by omor1** [comment]
I don't think umurmur can currently use password-protected private keys. Removing the password from an existing key is fairly simple though (as long as you know the password, that is).

Password-protected private keys are not often used, from my understanding. Either the password is stored in some configuration file, which defeats the purpose of the password, or it is input by the user every time the server restarts, which is impractical.

**Comment by juadde** [comment]
I think you are right, I will close the thread then.
Thank you for your answer.
