### ISSUE TITLE
uMurmur still generates self-signed certificates even if letsencrypt certificate is specified.

### ISSUE THREAD

**Issue by ghost** [umurmur/umurmur#118]
I'm running uMurmur 0.2.17 on Void Linux, x64 with 4.9.40 kernel. I have noticed when I set the server to use Letsencrypt Certificates like that:
```
certificate = "/var/lib/acme/live/<mysite>/fullchain";
private_key = "/var/lib/acme/live/<mysite>/privkey";
```
umurmur uses the LE certificate, but still adds two entries, as depicted here: 
![zrzut ekranu 17](https://user-images.githubusercontent.com/15038890/28995238-551f254c-79e4-11e7-852d-0b79406d49c4.png)
Those are being regenerated on each umurmur restart.
Is there a way to remove those certificates or disable generating of those certificates?

**Comment by fmorgner** [comment]
Might be an issue in our OpenSSL backend. I will look into it

**Comment by mirolm** [comment]
I can second this issue. Again OpenSSL backend, Debian Stretch. This does not happen with mbedTLS. 

One time in the past i noticed that umurmur managed to overwrite my letsencrypt certificate with a self-generated one. I suppose it can happen if umurmur is run with root, so it can write on certificates, and backend is OpenSSL, so self-signed certs are generated.

**Comment by mmelvin0** [comment]
Not sure if this is the same as what @mirolm is seeing but this happens repeatably w/OpenSSL on Alpine Linux if uMurmur fails to read the certificate or private_key file.
