### ISSUE TITLE
UMurmur startup issue, permissions problem?

### ISSUE THREAD

**Issue by stonelike** [umurmur/umurmur#119]
Hello.  I looked around, but wasn't sure where else to ask for help on this issue, so I hope this is an acceptable place to do so.

I recently installed umurmur in arch linux, and am trying to use it with a .PEM certificate and key.  I believe I have the credentials set correctly in umurmur's config file, and I know the key itself works with another service.

However, when I try and run umumrur as a systemd service, I get this output;

`● umurmur.service - Minimalistic Mumble server
   Loaded: loaded (/usr/lib/systemd/system/umurmur.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-09-22 13:16:20 PDT; 6min ago
 Main PID: 10706 (code=exited, status=1/FAILURE)

Sep 22 13:16:20 machine systemd[1]: Starting Minimalistic Mumble server...
Sep 22 13:16:20 machine systemd[1]: Started Minimalistic Mumble server.
Sep 22 13:16:20 machine umurmurd[10706]: INFO: Setting SCHED_RR prio 1
Sep 22 13:16:20 machine umurmurd[10706]: WARN: Failed to set scheduler: Operation not permitted
Sep 22 13:16:20 machine umurmurd[10706]: FATAL: Could not read private key file /etc/ssl/server-key.pem
Sep 22 13:16:20 machine systemd[1]: umurmur.service: Main process exited, code=exited, status=1/FAILURE
Sep 22 13:16:20 machine systemd[1]: umurmur.service: Unit entered failed state.
Sep 22 13:16:20 machine systemd[1]: umurmur.service: Failed with result 'exit-code'.
`

It appears that umurmur cannot read my private key, which I think is the main problem it's having, and I'm not sure if this is a configuration error or a bug.  The key is owned by root, which may be the core problem.  However, I was reading in earlier umurmur issues that there was some debate about whether umurmur could read keys as root on startup before dropping permissions, or whether it should have its' own umurmur-owned private key instead; so I'm unclear on whether I should make a private key owned by umurmur (or let it generate its' own), or whether I have not configured umurmur to access a root-owned key properly.  I would rather not run umurmur itself as root.

Clarification on a reasonable setup would be appreciated.  Thank you.

**Comment by C4K3** [comment]
The issue is indeed that the key is owned by root. The systemd .service for umurmur in Arch Linux tells it to run umurmur as the umurmur user: https://git.archlinux.org/svntogit/community.git/tree/trunk/umurmur.service?h=packages/umurmur
So it won't be able to read any key owned by root (unless it's readable by anyone.)

The best solution would be to change the ownership of the key to umurmur.

I believe the issue you're referring to is #105. Basically umurmur can switch user, but not when the -d flag is passed, which systemd does.

**Comment by stonelike** [comment]
Alright, thank you C4K3.  I will make a umurmur-owned key and roll with
that then, as that should work well enough for my purposes.  Thanks for
clarifying how it works.



On Sep 24, 2017 04:54, "C4K3" <notifications@github.com> wrote:

The issue is indeed that the key is owned by root. The systemd .service for
umurmur in Arch Linux tells it to run umurmur as the umurmur user:
https://git.archlinux.org/svntogit/community.git/tree/
trunk/umurmur.service?h=packages/umurmur
So it won't be able to read any key owned by root (unless it's readable by
anyone.)

The best solution would be to change the ownership of the key to umurmur.

I believe the issue you're referring to is #105
<https://github.com/umurmur/umurmur/issues/105>. Basically umurmur can
switch user, but not when the -d flag is passed, which systemd does.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/umurmur/umurmur/issues/119#issuecomment-331705039>, or mute
the thread
