### ISSUE TITLE
Featureset compared to regular Mumble?

### ISSUE THREAD

**Issue by fuzzy76** [umurmur/umurmur#132]
I would love to know the differences in features before I can evaluate if this is a good fit for my clan. I could not find anything in either the web site, the project readme or the wiki.

**Comment by snowblind** [comment]
umurmur just a replacement server for Mumble that can run on low end linux hardware (rpi, routers, etc.) with reduced features compared to the full mumble server. depending on how big your clans is you would want to use a hosted mumble server they are cheap just do a search

**Comment by fdutheil** [comment]
As far as I can tell (I don't use advance feature, and my community is really small), there is no users management which can be good or bad (no management at all once umurmur is installed (set the server password and "forget"), no additionnal management UI required to facilitate users management, etc.), and you can't dynamically move/reconfigure channels from a mumble (admin) client, as they are statically defined in umurmur configuration.
Nothing I do mind, here, that's even why I migrated to umurmur (thanks to the [mumble-django](https://bitbucket.org/Svedrin/mumble-django/wiki/Home) author for his work, btw).
