### ISSUE TITLE
ca_path option reasoning

### ISSUE THREAD

**Issue by unterwulf** [umurmur/umurmur#135]
I wonder what is the reason for the ca_path option. I'd expect that when the option is set all clients are obliged to have CA-signed certificates that can be verified with one of CA certificates located at ca_path. But what I see in the code is that clients' certificates are indeed verified against CA certificates, but the only outcome of failure is a message in the log. From my point of view the connection should be denied in this case.

I'd love to hear from anyone using this option what is its use with current implementation.

**Comment by mr-infty** [comment]
The configuration option `ca_path` is used in a function call to `SSL_CTX_load_verify_locations`, as the argument `CApath`. According to [this](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_load_verify_locations.html), in this directory are *trusted*, and used for verification purposes:

> SSL_CTX_load_verify_locations() specifies the locations for ctx, at which CA certificates for verification purposes are located. The certificates available via CAfile and CApath are trusted.

**Comment by mintware** [comment]
Nicolas, thank you for your reply, but my question was about practical use of the option. I had studied the code before asking the question. What you said makes sense, but in fact whether a certificate is trusted or not makes no difference to uMurmur. The client will be allowed to join anyway with no restrictions.

**Comment by unterwulf** [comment]
Nicolas, thank you for your reply, but my question was about a practical use of the option. I had studied the code before asking the question. What you said makes sense, but in fact whether a client has a trusted certificate or not makes no difference to uMurmur. The client will be allowed to join anyway with no extra restrictions.

**Comment by omor1** [comment]
Doesn't that set the path for uMurmur's root CA chain? It only works with OpenSSL, if I recall correctly.

**Comment by unterwulf** [comment]
omor1, indeed SSL_CTX_load_verify_locations() has this effect as well.

> When building its own certificate chain, an OpenSSL client/server will try to fill in missing certificates from CAfile/CApath, if the certificate chain was not explicitly specified (see SSL_CTX_add_extra_chain_cert, SSL_CTX_use_certificate).

I've verified this and it seems to actually behave like this. But this could also be accomplished by placing all the chain into the server certificate file, so although this option provides some extra configuration flexibility in terms of certificate storage it's not 100% necessary.

I think you answered my question. Thanks, omor1!
