### ISSUE TITLE
Website not generating proper certificate

### ISSUE THREAD

**Issue by neheb** [umurmur/umurmur#137]
No idea where to put this.

https://umurmur.net/ errors with a certificate pointing to github.com

GitHub has support for Let's Encrypt now: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by Mikaela** [comment]
It looks like the A records are pointing to wrong IP addresses comparing to [GitHub help](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider). After doing that, I think the CNAME file would need removing and adding [or using the GitHub tool for that](https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/).

**Comment by bentley** [comment]
Updating the umurmur.net DNS records as in the links above should be enough to fix the certificate problem.

**Comment by fmorgner** [comment]
Fixed
