### ISSUE TITLE
Wrong encryption key in CryptState_setKey

### ISSUE THREAD

**Issue by feinerer** [umurmur/umurmur#142]
When setting the encryption key in https://github.com/umurmur/umurmur/blob/55689f8918dde299c47c06eee4b8eda4a1c9889e/src/crypt.c#L89 shouldn't it match the (decryption) key `cs->raw_key`, similar to the procedure when generating a key: https://github.com/umurmur/umurmur/blob/55689f8918dde299c47c06eee4b8eda4a1c9889e/src/crypt.c#L77-L78?

This would also match the behavior in the Murmur server: https://github.com/mumble-voip/mumble/blob/c3a9f0dcb40d159d6f2dfcfa1a1e7c946ebc7ed1/src/CryptState.cpp#L45-L52

As `CryptState_setKey` is nowhere used in the umurmur code base this is a functional no-op. But for correctness this should be fixed (or `CryptState_setKey` removed).

If this is correct I can create a pull request if desired.

**Comment by fatbob313** [comment]
Thanks! Seems correct. Sorry about the late reply. Please send a pullreq if you want or I can just add this change.
