### ISSUE TITLE
Why linked channels are only used when whispering?

### ISSUE THREAD

**Issue by unterwulf** [umurmur/umurmur#144]
Does anyone know why in uMurmur linked channels are only used when whispering?
It seems not to be the case for the official Murmur server. As far as I can see the initial implementation of linked channels in uMurmur was also different. The audio was sent to linked channels even for _Normal talking_, but the commit 477a4a1 changed this.

Is there anyone who witnessed this and remembers why this was done?

**Comment by fkahhaleh** [comment]
You have just saved me a lot of time and effort @unterwulf  with your remark!
I have spent the better half of the day trying to figure out why my umurmur installation (on a Synology NAS device) was not working correctly when it came to the Linked Channels configuration and behavior! 

Thank you!

**Comment by fatbob313** [comment]
It's a misinterpretation of the Murmur imlementation. Should be fixed with #152.
