### ISSUE TITLE
Drop privileges in nodaemon mode

### ISSUE THREAD

**Issue by grmat** [umurmur/umurmur#154]
`switch_user()` to drop privileges is only called when flag `-d` is not set. Is there any specific reason for this?

Because I was confused when I entered the user name to the config and dropping privileges didn't work
a) when launching via init system that sets `-d` for monitoring purposes
b) when testing it from the command line

I think that condition should either be removed or at least documented. I could provide a patch for any of the options if you wish.

See https://github.com/umurmur/umurmur/blob/master/src/main.c#L365

**Comment by fatbob313** [comment]
There is a lengthy discussion in #105 re this. Personally I have no strong opinion (I use it only for testing/debugging).

**Comment by grmat** [comment]
I see. Haven't found it when searching for "privilege" etc., thanks for the reference
