### ISSUE TITLE
Doesn't install conf into CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by z0rti** [umurmur/umurmur#167]
when i build it with -DCMAKE_INSTALL_PREFIX=/opt/umurmur
the conf should go in /opt/umurmur/etc instead
```
$ make install
[...]
-- Installing: /etc/opt/umurmur/umurmur.conf
-- Installing: /opt/umurmur/bin/umurmurd
[...]
```

**Comment by dvzrv** [comment]
That is in fact the correct location according to [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) and the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) - see the [cmake documentation in regards to CMAKE_INSTALL_FULL_SYSCONFDIR](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#special-cases)

**Comment by z0rti** [comment]
OK i see, it's not a bug, thanks for explaining
