### ISSUE TITLE
Logging in as admin?

### ISSUE THREAD

**Issue by l29ah** [umurmur/umurmur#171]
I've set `admin_password` in the config file, yet i still can't log in as one, as it tells me that the password for an unregistered user account is invalid, regardless of the nickname i use, `L29Ah`, `admin`, or `SuperUser`. How do i log in?

**Comment by fatbob313** [comment]
In Mumble: menu 'Server' -> 'Access tokens...'. Add the admin password. Disconnect and reconnect and you should have admin privileges.

**Comment by Christoph111** [comment]
can you move users if your´re admin? tried but did not work....
