### ISSUE TITLE
What would be the maximum no of users i could have connected with umurmur ?

### ISSUE THREAD

**Issue by robertnax** [umurmur/umurmur#173]
Is it possible at all to have lets say 500 concurrent users running towards this server ? if not anyone would know where the limitation is if you want to have one server to handle many concurrent connections ?

and sorry not sure how to set a 'question' tag on this

**Comment by fatbob313** [comment]
It's probably possible but it depends very much on the hardware you run the server on and available network bandwidth. There are no built in limits concerning number of clients. uMurmur is not designed for this scenario though; it's single threaded so it won't take advantage of multiple processors, the user administration and access rights management are simplistic compared to Murmur. I'd go for Murmur if I expect 500 concurrent users on my server.

**Comment by robertnax** [comment]
Yes okay that makes sense thanks
