### ISSUE TITLE
Anyone can guide through how to build on windows 10 ?

### ISSUE THREAD

**Issue by gorive** [umurmur/umurmur#174]
Is it possible to build and run umurmur on windows ?

**Comment by fatbob313** [comment]
I don't know. You could try build it in a Cygwin environment.

**Comment by robertnax** [comment]
Not sure it helps but i managed to build it on WSL2 ( Ubuntu running on Linux subsystem on windows 10 ) - it did require quite alot of extras than what is specfied in the build-guide - i might put one up what i had to do before i was able to build it.
