### ISSUE TITLE
umurmur can't start without specifying config file manually

### ISSUE THREAD

**Issue by doesnmisclown** [umurmur/umurmur#186]
> Error in config file /usr/local/etc/umurmur.conf line 0: file I/O error

if I'm run with `-c /usr/local/etc/umurmur.conf` it starts normally
OS: FreeBSD 13.2-RELEASE
umurmur version: 0.2.17_2 (from FreeBSD repositories)

**Comment by fatbob313** [comment]
Default config file location is '/usr/local/etc/umurmur.conf' and umurmur can't find any file there.

**Comment by doesnmisclown** [comment]
Oh, FreeBSD version specify file in /usr/local/etc/umurmur/umurmur.conf lol
