### ISSUE TITLE
umurmurd memory leak?

### ISSUE THREAD

**Issue by snowblind** [umurmur/umurmur#52]
umurmurd memory usage is slowly growing while a users are connected to it.
After running most of the day yesterday with 4 users connected to it. umurmur is using 61meg RES 63megVIRT 960kSHR The SHR memory usage stays the same.
I could watch the memory usage grow by ~5-17 bytes every sec. while they were connected.

I have been looking into this after I noticed umurmurd reported by htop was using 76.3 of the 231megs my system has. The above stats are 26.6%.

I just restarted umurmurd and I get a .5% number with just connected and the numbers are not growing

With just me connected the memory usage is not growing at all. I wonder if it happens just when there is talking going on.

More info later....

I am using the version I last pull requested.

**Comment by fmorgner** [comment]
can you provide more information?

**Comment by snowblind** [comment]
Yeah I fixed it I hit enter in the topic and it posted just that :/

**Comment by fmorgner** [comment]
:) i will try and see if i can figure it out using the clang memory sanitizer.

**Comment by fmorgner** [comment]
Which TLS backend are you using? There were some issues with openssl never freeing any memory, maybe its related to that?

**Comment by snowblind** [comment]
ldd /usr/local/bin/umurmurd
        /usr/lib/arm-linux-gnueabihf/libcofi_rpi.so (0xb6fcf000)
        libconfig.so.9 => /usr/lib/arm-linux-gnueabihf/libconfig.so.9 (0xb6fb2000)
        libprotobuf-c.so.1 => /usr/local/lib/libprotobuf-c.so.1 (0xb6fa3000)
        libpolarssl.so.0 => /usr/lib/libpolarssl.so.0 (0xb6f4b000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6f3c000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6f14000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6de4000)
        /lib/ld-linux-armhf.so.3 (0xb6fdd000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6dc5000)

**Comment by snowblind** [comment]
It seems talking is what makes the memory usage reported by htop jump by 4k a sec every time someone talks if user more than 1

The RES column in htop jump like this 2000 2004 2008.

Can point me to some good linux memory debug articles. 
I do a search later on Google for some info also, I just can really get into it right now though.
I hope this is not  my SHM code. I don't think I am not freeing memory that I should as the memory is alloc by the linux SHM API. But maybe I am holding a pointer keeping something else from freeing its memory.

**Comment by fmorgner** [comment]
I think I figured it out. The problem kind of lies in your SHM code, but I think you are not to blame.

Here is what happens:

You call Util_clientAddressToString(...) fairly often. This function returns a pointer to heap memory which has to be freed when you are done with it. You might want to store it in a variable, strncopy it and then free the pointer stored in the variable.

I think its not your fault, since even I (who introduced the Util_* APIs) couldn't get it right, and my code is leaking too.

Your extensive use of that function just revealed the problem. I will look into possibilities on how to fix this issue as elegantly as possible. If you've got any ideas, feel free to open a pull request.

**Comment by fmorgner** [comment]
The "large" leak is fixed in the current master.

**Comment by snowblind** [comment]
OK.. Using that version now will keep an eye on it.

**Comment by snowblind** [comment]
Nice work VIRT 28104 RES 968 SHR 964 after 1:14:16 of reported cpu time with users on it

**Comment by fmorgner** [comment]
28MB still feels like a lot to me, but maybe I'm mistaken. I will close the issue once i fixed the other leaks as well.

**Comment by snowblind** [comment]
Bah I should look at what I am typing and swapping windows to see while getting talked to.. 

VIRT 2664 1216 RES 964SHR 3:52.20 CPUTIME

**Comment by fmorgner** [comment]
All leaks should be closed now.
