### ISSUE TITLE
Null pointer dereferences

### ISSUE THREAD

**Issue by TinnedTuna** [umurmur/umurmur#63]
Under memory pressure, umurmur may dereference a null pointer in several places. I have a patch to wrap malloc and calloc with some logic to do error checking, but I can't get umurmur to build (I tried on Linux Mint 17.1, OpenBSD 5.6 and FreeBSD 10.1-RELEASE), so I can't vouch for these patches.

The problems are:

./src/server.c:97 (The variable is dereferenced at line 128)
./src/server.c:99
./src/server.c:101
./src/messagehandler.c:287
Throughout ./src/message, starting at line 287 through to 373.
./src/channel.c:225
./src/channel.c:383

There is also the potential for integer overflow leading when performing malloc.

./src/messages.c:395
./src/messagehandler.c:287
./src/messagehandler.c:866

Like I say, I can share my patch, but I haven't managed to build umurmur even without my patch.

**Comment by fmorgner** [comment]
Thanks for reporting! I will look into it.

**Comment by fmorgner** [comment]
@TinnedTuna could you check my patch against yours? Thanks!

**Comment by omor1** [comment]
@fmorgner I noticed a couple errors in the fix, take a look at #66.

**Comment by TinnedTuna** [comment]
Hi @fmorgner,

My patch was substantially different from yours; I wrapped up malloc in a "safe" wrapper function which always checked for a null-return value before returning. I then used this "safe" malloc everywhere that malloc or calloc was used, and deleted the repeated error checks.

My function was as follows, in a file called "memory.c", declared in "memory.h":

```C
void * Memory_safeMalloc(size_t nmem, size_t size) {
        // Check if we're going to overflow.
        if (size && num > SIZE_MAX / size)
                Log_fatal("Request for memory would've overflowed.");

        // Allocate the memory requested.
        void * retPtr = malloc(nmem * size);

        // Check if we had an error.
        if (retPtr == NULL)
                Log_fatal("Out of memory.");

        return retPtr;
}
```

I'm not sure if size_t is the right type for nmem.

My patch also changed at least one p = malloc(...); memset(p, 0, ...) to calloc, in a safe wrapper.

In your patch, I noticed that ./src/messages.c:287 through 373 were untouched, did you add null-check guards into all the functions which the ptr is being passed into?

**Comment by fmorgner** [comment]
I think your solution is much more elegant than mine. I think i overlooked that malloc-memset you mentioned when i tried to change all malloc-memset combinations into calloc. I'd be glad if you could email your patch to me, since as I said it feels much more elegant than mine.

regardin messages.c i think you are talking about the "msg" pointer, which is checked in Msg_create_nopayload as far as i can tell.

**Comment by TinnedTuna** [comment]
Hi @fmorgner,

I've sent an email with patch(es) attached to the email listed on your profile.

**Comment by fmorgner** [comment]
Thanks!

**Comment by omor1** [comment]
I'm not sure if I'm a fan of replacing malloc/calloc like this. It makes it non-obvious what memory allocation is going to do and can get you in the habit of not checking for allocation failure.

On the other hand, it reduces code reuse, which I like.

**Comment by omor1** [comment]
I've noticed a style issue – some parts of the code check for null with
````C
if (!pointer)
````
while other parts use
````C
if (NULL == pointer)
````

I think one should be standardize on and used throughout instead of using both.

**Comment by TinnedTuna** [comment]
@omor1 Wrapping allocation is definitely a double edged sword. On the one hand, if you grep for malloc, calloc, etc, you can easily audit them for correct usage in one canonical place, and make sure it's well written, well tested, and so on. This makes it easy to avoid unexpected crashes and the occasional memory safety vulnerability.

Another benefit is that if you do wish to provide a different allocation strategy, there is exactly one place to change it. I'm not a fan of this, as it has caused serious problems for other projects.

On the other hand, it is (as you say) non-obvious. It might not be clear to the consumer of the API that a null check, and overflow check are not required. There's also a small performance over-head to each method call, and there is, in my implementation, an overflow check is occurring for all calls, when it's only needed in a fraction of cases.

My personal preference is to go with the solution I've provided; it may make it easier to spot these kinds of problems in the future. But I am also very aware that umurmur is aimed at low-resource devices, where these kind of checks can cause performance issues. Perhaps a pragmatic solution (volunteer time permitting!) would be to benchmark umurmur as it stands, then measure the performance with my patch. If the effect is unbearable, a different solution must be proposed.

I also agree that null-checking should be standardised. When reading through the code, I did notice at least 3 different ways of doing the same thing. I don't mind which is used throughout, as long as it's just one. I'd say that for that kind of clean up and discussion, a separate issue might be a better place for it though?

**Comment by fmorgner** [comment]
I agree with both of you. As you've already mentioned, hiding allocation behind some API tends to "obfuscate" what is going on. But I think as long as the API is well-designed (like @TinnedTuna's patch) the intend should be clear and thus it would benefit the programmer a lot more than it hurts.

Regarding the performance overhead: I'm not sure but shouldn't the compiler be allowed to inline the function calls? Even if it isn't I believe that these functions would impose a rather small overhead, considering we would have to do a NULL-Check+Die in a lot of places anway. I'm in strong favor of the proposed solution and if there are no strong opinions against it I am going to merge it into the code.

As far as style issues go: I think there are some other open points that need to be standardized in another discussion. All input is very welcome!

**Comment by fmorgner** [comment]
I have merged @TinnedTuna's patch into the "development" branch. Very basic testing seems satisfactory.

**Comment by omor1** [comment]
I think the performance overhead is likely to be rather small in most use cases. Perhaps we should take a look at how larger C-based projects handle similar situations – do they use plain malloc/calloc, or do they use a wrapper function?
Aside, I submitted #67 and #68 for another couple NULL check memory allocation errors I found.

I'll open up another issue for the style standardization discussion.

**Comment by TinnedTuna** [comment]
@omor1 wrapping malloc is common in security focused C programs. For instance, vsftpd provides vsf_sysutil_malloc and vsf_sysutil_realloc in sysutil.c, and openssh provides xalloc and xcalloc in xalloc.c.

They both have slightly different wrappers to the one I've provided. For instance, vsftpd's vsf_sysutil_malloc and xmalloc both actively guard against allocating size 0, which mine misses out. 

openssh's xcalloc checks for overflow of the arguments, whereas mine assumes that calloc is safe in the face of overflowing arguments. openssh's xmalloc does not check for overflow, but it only takes one argument of type size_t.

Having looked at these two projects, I'd probably make a few modifications:

  1. Add an overflow check into the calloc wrapper.
  2. Add a check that nmem != 0 to the malloc and calloc wrapper. We want size * nmem != 0, and the overflow check also checks that size != 0; therefore, we only need to check nmem.
  3. Use SIZE_T_MAX in the overflow check in place of a simple SIZE_MAX.

Finally, #67 and #68 should be fixed on the development branch.

**Comment by fmorgner** [comment]
I am closing this issue since we moved to using the safe wrappers. Feel free to reopen the issue if I am mistaken.
