### ISSUE TITLE
`tlsi_openssl`: intermediate certificates in certificate file are ignored

### ISSUE THREAD

**Issue by andres-erbsen** [umurmur/umurmur#64]
When running `umurmurd` compiled with openssl and having added concatenated leaf and intermediate certificates to the certificate file specified in the configuration, only the leaf gets presented to clients. Therefore, in the common case that the intermediate is necessary for creating a trust path from a trusted root to the server certificate, the connection will fail with a certificate error. This would be nice to fix because (to the best of my knowledge), the only way to get both a subdomain and a working TLS certificate for free (through freedns.afraid.org and [WoSign](https://www.ohling.org/blog/2015/02/wosign-free-2y-ssl-certificate.html)) ends up with the user having a certificate that requires an intermediate (or two) to work.

I am guessing this happens because `ssli_openssl.c` uses `PEM_read_X509` to read the certificate file, and `pem_read_x509` documentation says that it `process an X509 certificate using an X509 structure`, which sounds to me like only a single certificate (not a chain) is read. Indeed, later on `SSL_CTX_use_certificate` is called, whose documentation explicitly mentions that intermediates need to be added separately. Perhaps `SSL_CTX_use_certificate_chain_file` would be a better fit.

**Comment by omor1** [comment]
What order are you concatenating the certificates in? I had an issue previously (#50) where PolarSSL and OpenSSL wanted to have the certificates concatenated in opposite order.

**Comment by fmorgner** [comment]
@andres-erbsen could you please verify that this commit resolves your issue? Thanks!

**Comment by andres-erbsen** [comment]
Tested using `openssl s_client -connect myserver:64738 -verify_return_error -showcerts` and the standard Mumble client: the server cert and intermediates are presented and the connection works. Thanks a bunch!

**Comment by fmorgner** [comment]
Glad that helped! Have fun!

**Comment by fdutheil** [comment]
Hi,
Sorry to intervene so late and on a closed issue, but it would be really nice to have a release including this fix, as for now for example even the latest available (0.2.16 on FreeBSD 11) can't properly present its certificate to clients.
