### ISSUE TITLE
mbedtls2 support

### ISSUE THREAD

**Issue by p5n** [umurmur/umurmur#72]
polarssl-1.* is known as mbedtls-2.* now. Could you please fix the build against mbedtls2?

Here is dirty hack that builds umurmur against mbedtls:
https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/umurmur
(see mbedtls2.patch)

**Comment by fmorgner** [comment]
i just merged #71. Could you verify if that does the job?

**Comment by p5n** [comment]
looks fixed, thank you
