### ISSUE TITLE
[feature request] priority speaker

### ISSUE THREAD

**Issue by siikamiika** [umurmur/umurmur#76]
Assuming it's a feature mainly handled at the client side with the server only telling who has it, priority speaker shouldn't consume much resources. I'd be happy to contribute, but I'm not familiar with the codebase or C conventions in general.

Currently, requests to adjust the priority speaker status of a user seem to be ignored here:
https://github.com/umurmur/umurmur/blob/ae8259343df8cf5dfbe5eda22c58c222d36a5499/src/messagehandler.c#L452
The option to change somebody's priority speaker status becomes available in the Mumble UI when one adds the server's `admin_password` to access tokens, but the server responds to requests with the text "Not supported by uMurmur".

Thanks!

**Comment by halcyforn** [comment]
this is basic option in mumble and should be implemented.
