### ISSUE TITLE
Support ECDHE-RSA-AES128-GCM-SHA256

### ISSUE THREAD

**Issue by l2dy** [umurmur/umurmur#77]
A very strict one for mbed TLS:
l2dy@84ff6ec

**Comment by l2dy** [comment]
A very strict one for mbedtls:
https://github.com/l2dy/umurmur/commit/bc747cfb3405935960f2855f51c729c97bc47a8b

**Comment by fmorgner** [comment]
I like the idea, but do you know what the API would be for mbed TLS to make it configurable? If I remember correctly, GnuTLS supports configuration via string just like OpenSSL/LibreSSL. I think it would be nice to get the user the option to select the suites he wants to use, with us supplying some sane defaults.

**Comment by l2dy** [comment]
The only one I know is `mbedtls_ssl_ciphersuite_from_string`.

**Comment by l2dy** [comment]
How about using this from mumble-voip/mumble@7b086e8 ?
```
The OpenSSL cipher list in MumbleSSL::defaultOpenSSLCipherString()
evaluates to the following set of cipher suites, in order of preference:

  ECDHE-RSA-AES256-GCM-SHA384    (TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
  ECDHE-ECDSA-AES256-GCM-SHA384  (TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384)
  ECDHE-RSA-AES128-GCM-SHA256    (TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256)
  ECDHE-ECDSA-AES128-GCM-SHA256  (TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256)
  AES256-SHA                     (TLS_RSA_WITH_AES_256_CBC_SHA)
  AES128-SHA                     (TLS_RSA_WITH_AES_128_CBC_SHA)
```
