### ISSUE TITLE
[Feature request] Add option to not show client's IP addresses in user information window

### ISSUE THREAD

**Issue by C4K3** [umurmur/umurmur#81]
It seems mumur has a similar option called obfuscate.

We had a guy on my mumble server come on and started threatening to DDoS people, by saying off their IPs and geographic area. Not much happened, but people have been voicing concerns.

**Comment by fmorgner** [comment]
Will look into this. Thanks

**Comment by inklit** [comment]
Please add this option. It's a security risk to give out users IP addresses to people who are not server administrators.
