### ISSUE TITLE
ssli_openssl.c doesn't restrict connections to be TLS 1.0 or greater

### ISSUE THREAD

**Issue by mkrautz** [umurmur/umurmur#84]
Murmur itself requires TLS 1.0 or greater, but the SSL implementation in ssli_openssl.c seems to use the `SSLv23_server_method()` method without calling `SSL_CTX_set_options()` to limit the SSL/TLS versions the server will support. In practice, this should mean that the server will allow SSLv2 connections (unless you use an OpenSSL where this is blacklisted) and SSLv3.

**Comment by fmorgner** [comment]
Published "hotfix"
