### ISSUE TITLE
mbedTLS backend only uses TLS 1.2, breaks backwards compatibility with Linux 1.2.x clients

### ISSUE THREAD

**Issue by mkrautz** [umurmur/umurmur#90]
See

https://github.com/umurmur/umurmur/blob/master/src/ssli_mbedtls.c#L176

This means that Mumble packages from for example Debian and Ubuntu -- and most other distros -- can't connect to uMurmur built with mbedTLS, because Mumble 1.2.x on Linux only uses TLS 1.0.

(Binary packages from mumble.info of 1.2.x use a patched version of Qt 4 which allows TLS 1.1 and TLS 1.2 -- so OS X and Windows clients aren't affected.)

**Comment by fmorgner** [comment]
#103 is merged. Can you verify if that solve the issue?

**Comment by mkrautz** [comment]
Sorry, I don't have any easy way to test uMurmur with mbedTLS.

The issue was more of an FYI.

The change looks correct to me. Feel free to close if you believe it is fixed. :-)

**Comment by fmorgner** [comment]
I tested it on my machine, and it seems to work.
