### ISSUE TITLE
Server using old encryption standard

### ISSUE THREAD

**Issue by Kamoenix** [umurmur/umurmur#93]
Hi,

I've installed the uMurmur server on my Synology NAS from the SynoCommunity page and done the initial setup - changed the channels / passwords ect.

When I try and connect to the server I get the following error "This server is using an older encryption standard, and is no longer supported by the modern version of Mumble".
 ##
I'm using the latest version of the server which is on the community  - 0.2.16-6. 
Mumble version - 1.2.16
DSM version - DSM 6.0.1-7393 Update 1

If you could provide some help with how to get around this problem I would greatly appreciate it.

Thanks

**Comment by l2dy** [comment]
You need to build it yourself.

**Comment by Diaoul** [comment]
Or wait for the next release.

**Comment by fmorgner** [comment]
Hoping to release soon.
