### ISSUE TITLE
Dropping privileges before setting scheduler

### ISSUE THREAD

**Issue by alarig** [umurmur/umurmur#94]
When you don’t run the daemon as root, the privileges are dropped before the scheduler is setted.

> Jul 25 20:52:18 bulbizarre uMurmurd[24400]: Switch to user 'murmur' group 'murmur'
> Jul 25 20:52:18 bulbizarre uMurmurd[24400]: Setting SCHED_RR prio 1
> Jul 25 20:52:18 bulbizarre uMurmurd[24400]: Failed to set scheduler: Operation not permitted

This is due of dropping privileges before setting scheduler (lines 116 and 223 in main.c). And regarding to [man 2 sched_setscheduler](http://linux.die.net/man/2/sched_setscheduler) “In Linux kernels before 2.6.12, only privileged (CAP_SYS_NICE) processes can set a nonzero static priority (i.e., set a real-time scheduling policy).
Since Linux 2.6.12, the RLIMIT_RTPRIO resource limit defines a ceiling on an unprivileged process's static priority for the SCHED_RR and SCHED_FIFO policies. The rules for changing scheduling policy and priority are as follows: [all the cases]”.

So, the scheduler should be setted before dropping privileges.

**Comment by rixx** [comment]
Seconding, issue occurs on my machine, too. Running umurmur with root privileges solves the problem, but should not be necessary.

```
INFO: uMurmur version 0.2.16a ('Agrajag') protocol version 1.2.4
```
