### ISSUE TITLE
Suggestion: bindport6 should default to bindport and not the default Murmur port if not defined

### ISSUE THREAD

**Issue by niemalsnever** [umurmur/umurmur#97]
Hi, since I just had the problem that 2 users wanted to run a µmurmur instance on the same machine. Since the config template I used for my instance did not contain the bindport6 directive, I did not specify the bindport6 directive, only bindport. Therefore µurmur bound to the port I specified for IPv4, and to 64738 for IPv6. When the second user set up his instance, he did not not know about the bindport6 directive either, so he did not specify it, causing his instance to be unable to start, since it tried to bind to 64738 for IPv6 where my instance was already listening.

For that reason I'd like to suggest to have bindport6 default to bindport if it's not specified. Of course that behaviour should be documented, but as it stands now, it should be documented that bindport6 defaults to 64738 if not specified.

This happened using µmurmur 0.2.16a

**Comment by C4K3** [comment]
+1

**Comment by fmorgner** [comment]
Merged fix by @C4K3

**Comment by niemalsnever** [comment]
Thanks to both of you!
